[package]
name = "stacks-replay-wasm"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { workspace = true, features = ["derive"] }
clarity = { path = "../../clarity", default-features = false, features = ["testing"] }
clarity-cli = { path = "../clarity-cli", default-features = false }
libstackerdb = { path = "../../libstackerdb", default-features = false }
regex = { version = "1", default-features = false }
rusqlite = { workspace = true, features = ["blob", "serde_json"] }
serde_json = { workspace = true }
slog = { workspace = true }
slog-term = { version = "2.6.0", default-features = false }
stacks-common = { path = "../../stacks-common", default-features = false }
stackslib = { package = "stackslib", path = "../../stackslib", default-features = false }
indicatif = "0.18.4"

[target.'cfg(not(any(target_os = "macos", target_os = "windows", target_arch = "arm")))'.dependencies]
tikv-jemallocator = { workspace = true }

[dev-dependencies]
mutants = "0.0.3"
